name = "FEMBeamSolver"
uuid = "3b53a38b-07d6-41d7-8018-5495379a8465"
version = "0.1.0"
authors = ["Tanish Verma <verma.tanish@outlook.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1.12.0"
SparseArrays = "1.12.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
